name: ResourceRegen
main: com.example.oregen.OreRegenPlugin
version: 1.2.0 # Major feature update
authors:
  - LtHans
api-version: 1.20
commands:
  buildarea:
    description: Open the build area management GUI
    usage: /buildarea
  buildareaadmin:
    description: Open the admin build area management GUI
    usage: /buildareaadmin
